### ISSUE TITLE
Clarify options

### ISSUE THREAD

**Issue by nkh** [kristapsdz/lowdown#102]
it's very unclear in the documentation that BOTH --term-columns --term-width must be set in order to get  a wider rendering

**Comment by kristapsdz** [comment]
Can you propose an alternative in a pull request?  **--term-columns** sets the number of physical columns in the terminal (e.g. `$COLUMNS`), while **--term-width** is where line-breaking occurs on the line.

**Comment by kristapsdz** [comment]
Closed due to inactivity.

**Comment by kristapsdz** [comment]
Closed due to inactivity.
