### ISSUE TITLE
Discrepancies between mrkd manpages and lowdown manpages

### ISSUE THREAD

**Issue by grubles** [kristapsdz/lowdown#103]
Lowdown seems to introduce some whitespacing errors and misinterpretation(?) of markdown syntax to the man pages it generates.

See example screenshot below. Left is `lowdown`-generated, right is `mrkd`-generated. 

Notice the bulletpoint indentation is too far to the left. Text with double underscores (e.g. example_random_command)  is also generated incorrectly as partially underlined. Would this be fixed with somehow escaping the underscores intended to not be interpreted as markdown? 

![Screenshot_2022-07-26_16-11-30](https://user-images.githubusercontent.com/7411154/181106845-898f92ab-9bf8-4e7e-9e46-89f97778b1db.png)

Another error is sometimes bulletpoints aren't recognized altogether, and end up on the same line which ends up difficult to read. Here's an example after `The following error codes might occur`: 

![Screenshot_2022-07-26_16-43-56](https://user-images.githubusercontent.com/7411154/181108533-4fd543a3-2f65-4b03-a2d1-2f051ef60fbf.png)

**Comment by kristapsdz** [comment]
The first looks the same with **-tman** for `lowdown` and `pandoc` w/r/t horizontal spacing, giving the bullets a width of 2 and a left-justify at the margin, exactly as it should.  As for vertical, neither `pandoc` nor your tool are respecting that the list is a single-spaced list, not a double-spaced list, while `lowdown` is.  Just look at the markdown output in HTML.

Your second comes from bad Markdown: the list does not begin with a blank space.  pandoc has the same output as lowdown, here.

The only problem I can see here is, in the second example, that `lowdown` emits a superfluous vertical space before "Part of the key....".  It's something for me to look into...

**Comment by kristapsdz** [comment]
Closing due to lack of follow-up.  (I also can't find the given manpage to test.)  There have been many updates to the roff output in the meantime, hopefully these have fixed the last issues!
