### ISSUE TITLE
Render nroff block quotes without empty lines

### ISSUE THREAD

**Issue by fricklerhandwerk** [kristapsdz/lowdown#106]
**Problem description**

The following markdown

```
> **Warning**
>
> This is a warning.
```

Renders to nroff like this:

```
| Warning

| This is a warning.
```

which appears like two separate things.

To make the highlighted block appear as one, one can work around with

```
> **Warning** \
> This is a warning.
```

where the forced line break (`\`) is mandatory by markdown rules.

But this is ugly, surprising for readers, and if forgotten will break web rendering for converters which do not support the callout syntax, such as `mdBook`. It works without the forced line break on GitHub, though:

> **Warning**
> This is a warning.

**Proposal**

The original markdown should render to nroff like this:

```
| Warning
|
| This is a warning.
```

**Comment by kristapsdz** [comment]
Where are you seeing these vertical bars?  Both lowdown and pandoc **-tman** emit  similar **-man** in similar ways for this example.  Do you mean how **-tms** in pandoc wraps the block in `QS` and `QE`?  I thought about using this, but the effect is basically the same as `RS` and `RE`.

**Comment by fricklerhandwerk** [comment]
The described output is emitted by `-tman` and `-tms`.

I have no idea how pandoc does this, and I'm not sure why it's relevant. Is lowdown aiming for pandoc compatibility? What matters for the Nix use case is that HTML rendered by other tools looks similar enough to the terminal output in order not to be surprising or produce friction for contributors.

Also don't know what these `QS`, etc. tokens mean or in which context to even look them up.

**Comment by kristapsdz** [comment]
What is the exact command sequence you use to get those vertical bars?

**Comment by fricklerhandwerk** [comment]
I checked again, sorry for the delay.

Here is where it shows up as described: https://github.com/NixOS/nix/blob/ef0b48377d0fc79d70455c402ed4df4b18cb93dd/src/libcmd/markdown.cc#L14-L22

Indeed it doesn't for `-tman`: https://github.com/NixOS/nix/blob/ef0b48377d0fc79d70455c402ed4df4b18cb93dd/doc/manual/local.mk#L72

**Comment by kristapsdz** [comment]
I have no idea what's going on here.  I can't replicate this issue with any output mode of lowdown.  Using your original sample as *foo.md*:

```
% ./lowdown -tterm foo.md                                                                          
      | Warning
      | 
      | This is a warning.
```

Any other output format does not show the vertical bars.

I'm closing out this issue.  If you can actually replicate your problem with lowdown, please reopen it with the *exact command you used*.
