### ISSUE TITLE
Add standard options for help and version

### ISSUE THREAD

**Issue by prusnak** [kristapsdz/lowdown#107]
```
$ lowdown -h
lowdown: invalid option -- h

$ lowdown --help
lowdown: unrecognized option `--help'

$ lowdown -v
lowdown: invalid option -- v

$ lowdown --version
lowdown: unrecognized option `--version'
```

It's nice when these standard options work as expected.

**Comment by Mango0x45** [comment]
If you want documentation, you should read the manual (`man lowdown`)

**Comment by kristapsdz** [comment]
Running **-h** will get the usage message, so there's no need to implement it.  Do you have a use case for needing the version of `lowdown`?

**Comment by prusnak** [comment]
It's just good practice. If it cannot be implemented, fee free to close

**Comment by Disonantemus** [comment]
> If you want documentation, you should read the manual (`man lowdown`)

- Manual doesn't have version number.
- The only way to know that, was to check with package manager. `pacman -Qi lowdown`.

> Running **-h** will get the usage message, so there's no need to implement it. Do you have a use case for needing the version of `lowdown`?

- Yes, shows minimal flags, but shows an error: `invalid option -- 'h'`, if it shows the same info but without error, it's ok for me, for both: `-h` and `--help`.
- Later I did compile from git clone, but then I don't have an easy way to know which version I have.
