### ISSUE TITLE
liblowdown symbol visibility & leaks

### ISSUE THREAD

**Issue by paravoid** [kristapsdz/lowdown#109]
As one can observe with `nm --defined-only -gDC liblowdown.so`, a lot of symbols are visible in the shared library. Many of them not prefixed with `lowdown_`, such as e.g. `rcs2date`, `smarty`, all the `hbuf_*` ones, etc. which makes me wonder if these are exposed intentionally, or unintentionally. I suspect the latter.

To avoid exposing these symbols, there are are a few options (all TTBOMK):
- You can explicitly expose the ones you want (e.g. the ones in lowdown.h) to with `__attribute__ ((visibility ("default")))`, and then pass `-fvisibility=hidden` to the compiler to hide the rest
- You can add `#pragma GCC visibility push(default)` to the top of lowdown.h, and `#pragma GCC visibility pop` at the end, and similary pass `-fvisibility=hidden` to the compiler to set the default.
- You can pass `-Wl,--version-script=` to the compiler, pointing to a version script that has `{ global: lowdown_*; local: * }`, as its contents, to only expose symbols prefixed with `lowdown_`.

On a separate, unrelated note that is perhaps not worth opening a separate bug about: is the fact that the main lowdown binary linked against the static library rather than the shared one, intentional? This results in basically most of lowdown's code being duplicated in both binaries.

**Comment by kristapsdz** [comment]
Is using **-fvisibility=hidden** with the `pragma` macros portable?  If so, I'll add it.

**Comment by kristapsdz** [comment]
If the above looks good, please close out this report.  Tested on openbsd/clang, but should work anywhere.

**Comment by paravoid** [comment]
Looks great, thanks!
