### ISSUE TITLE
[regression] Non-defined PI macro emitted with -Tman

### ISSUE THREAD

**Issue by paravoid** [kristapsdz/lowdown#111]
```
$ lowdown -s -Tman regress/simple.md  | preconv -e UTF-8 | groff -Tutf8 -man -w w > /dev/null 
troff: <standard input>:183: warning: macro 'PI' not defined
```

I believe this was introduced with 47805345ee17f43f3b16fcb920fb572fc9d1c156.

**Comment by kristapsdz** [comment]
Yes, seems that's an **-ms** macro, not a **-man**.  Thanks!

**Comment by paravoid** [comment]
Thanks for looking into it! So is the fix reverting the aforementioned commit or something else? I'd like to backport the fix to this (either in isolation, or bundled with other bugfixes) to Debian before the bookworm release!

**Comment by kristapsdz** [comment]
Does the above commit fix this issue for you?  I use the width set by default in groff (5n) instead of the `PI` register.  If so, it'll be rolling into the next release, which I'll be doing in a day or so.

**Comment by paravoid** [comment]
Yes it does!
