### ISSUE TITLE
Suggestion for superscript

### ISSUE THREAD

**Issue by htopkill** [kristapsdz/lowdown#114]
You should use the same syntax than pandoc for superscript, 
^superscript^
Your syntax for superscript is very specific and not compatible with github/pandoc which are the 2 most used platform/application

**Comment by Disonantemus** [comment]
Think the same, instead of using a syntax that no one is going to use, because only work here.

**Comment by kristapsdz** [comment]
I privately received a patch to do this and will implement based on that.  Entitled issue reports like this are why open source development is so awful.  Ick.
