### ISSUE TITLE
typographical quotes not always replaced

### ISSUE THREAD

**Issue by step-** [kristapsdz/lowdown#115]
Bug report - version 1.0.0
```sh
printf '%s\n' '"A"  ' '"B"' '"C"  ' 'D'  | lowdown -thtml
```

Notice that double quote characters before B and after C were not replaced with smart quotes.
```
<p>&#8220;A&#8221;<br/>
"B&#8221;
&#8220;C"<br/>
D</p>
```

**Comment by kristapsdz** [comment]
Good catch!  Can you confirm that the above commit (which includes a regression test) fixes your issue and any similar ones you've found?  If so, I'll roll into the next release in a day or so.

**Comment by step-** [comment]
Yes, I can confirm that the fix is good, thank you!
I happened on this bug while comparing some markdown converters to each other. As you can well imagine, each program takes a different (not necessarily wrong) stance on smart quotes. Here's an example.

```
                                          other
<p>A“<br/>
B” “C<br/>
”D</p>
                                          /tmp/lowdown/lowdown
<p>A&#8221;<br/>
B&#8221;
&#8220;C<br/>
&#8220;D</p>
                                          pandoc
<p>A”<br />
B” “C<br />
”D</p>
```
