### ISSUE TITLE
Support for Pandoc's metadata block

### ISSUE THREAD

**Issue by paravoid** [kristapsdz/lowdown#117]
lowdown only supports the MMD inline metadata block. pandoc supports its own metadata block (`pandoc_title_block`), as well as the YAML metadata block (`yaml_metadata_block`), but not the MMD one.

This creates a situation where there is no common ground between the two tools, where one has the ability to create a document with inline metadata that works with both tools. #97 is proposing to at least ignore the YAML block, which seems like a valuable thing to do, but would not resolve the need to provide metadata in the command-line in those cases.

The [pandoc_title_block ](https://pandoc.org/MANUAL.html#metadata-blocks) format seems trivial enough that you may want to consider implementing it? I can give it a stab but I suspect you'll do it in 1/10th of the time :)

**Comment by kristapsdz** [comment]
This is now fully supported and will appear in the next version.  Please open a new issue if you find any problems in the current code!
