### ISSUE TITLE
Question: Accept gemini as an input format ?

### ISSUE THREAD

**Issue by m040601** [kristapsdz/lowdown#118]
First of all thank you for all your work and commitment in this tool.

I've been using it for a long time and I am utterly fascinated by it.
The cleaness, the "BSD spirit", the usefulness (spit to man, terminal etc), and the simplicity compared to other heavy weights like Pandoc are astonishing. Easely packageable and officially available for install for low underpowered ARM devices (ex, Archlinux ARM).

I use it a lot in shell scripts to do the static building of html blogs and pages.

My question is.

Would it be possible to add gemini markup as an input format ?

Since gemini "could" be almost considered as a "simple subset" of markdown would it take a lot of work to adapt lowdown to accept gemini input directly ? Or would there be any anoying "edge cases" that spoil that party ?

It is of course very easy to convert .gmi to .md. You dont need lowdown for that. A lot of simple tools can do that. Even simple awk, grep invocations can do that. But, itt would be nice to have it directly available from lowdown. With no extra scripting involved in the pipeline.

The "use case" is this. I am a fan of statically "baking" websites etc.
I am seriously playing with gemini as a "universal" and "simple poor" single source publishing format. From a gemini source, publish both a gemini website and a (simple) html site. And also  offline "poor" man pages, etc.

Thanks in advance.

PS: In the same vain would it be possible to have markdown not only as an input source, but also as an output format ?

The "use case" is having lowdown as a sort of "sanitizer", "cleaner" or "linter" for markdown input.

Pandoc can for example do "pandoc --from markdown --to markdown dirty.md clean.md"

**Comment by kristapsdz** [comment]
You can absolutely interface a parser you've written for Gemini with the lowdown(3) library by giving it a parse tree in the format described in lodwown.h and manpages.  This isn't something I'd support as native to lowdown, but I'm happy to respond to requests for information on library questions.
