### ISSUE TITLE
Bug with pipe_tables

### ISSUE THREAD

**Issue by Disonantemus** [kristapsdz/lowdown#119]
I think it's a "corner" case, because, if second line has 3 dashes instead of 1 for each header, renders ok. This table:
~~~
alfa|beta
-|-
21|22
~~~

---
Github renders:

alfa|beta
-|-
21|22

With *lowdown* it's rendered like this:
~~~
alfa|beta -|- gamma|delta
~~~

It's rendered as a table, with:  
- github
- pandoc
- http://markdown.pioul.fr/
- https://dillinger.io/
- https://stackedit.io/app# 

and maybe more ...

---

[Feature] request:  
- It's possible to have a "box of lines" like a spreadsheet with the table? (at least with html output)

**Comment by kristapsdz** [comment]
Thanks, fixed!  Please submit any feature requests in another issue, but I don't really take requests unless it's something accepted by other markdown formatters where lowdown doesn't match output.  In your case, CSS or the media-specific equivalent looks like it'd be the best fit.
