### ISSUE TITLE
[Bug] Metadata shown (shouldn't) with: -tterm -stterm -stms as main text

### ISSUE THREAD

**Issue by Disonantemus** [kristapsdz/lowdown#124]
> Metadata _shouldn't be shown_ with any of the following output modes:
  - -tterm (terminal output)
  - -stterm (standalone terminal output)
  - -stms (standalone roff output)

> With the following output modes works **as expected**
(metadata is not shown or created as metadata, not as _main text_):
  - (default: html)
  - -s (standalone html)
  - -sthtml
  - -tms
  - -tman

---

> Sample (-tterm):

~~~
> cat 0.md

---
Title: Captain's log
Author: Captain J-L Picard
...

alfa|beta
-|-
21|22

> cat 0.md | lowdown -tterm
    title: Captain’s log
    author: Captain J-L Picard

    alfa | beta
    -----|------
    21   | 22

> cat 0.md | lowdown -L
title
author

> cat 0.md | lowdown -X title
Captain's log

> pacman -Ss lowdown
extra/lowdown 1.0.2-2 [installed]
    A simple Markdown translator
~~~

---

> Extra  minor thing, when doing a query about metadata value, output is different depending on metadata format used to create it:

- yaml_metadata_block
~~~
> cat 1a.md
---
Title: Captain's log
Author: Captain J-L Picard
...
> cat 1a.md | lowdown -X title
Captain's log
~~~

- pandoc_title_block
~~~
> cat 1b.md
% Title: Captain's log
% Author: Captain J-L Picard
> cat 1b.md | lowdown -X title
Title: Captain's log
~~~

As you can see, the later (pandoc_title_block) includes word "Title: " in the output (not in the first one).

**Comment by kristapsdz** [comment]
Thanks for the report!  Tackling these one by one, I'll start with the pandoc title block. If you run it through pandoc, you'll see the same result: pandoc's title blocks depend on order, so the "Title:" and "Author:" in your example are part of the title block.  So there's nothing to fix here, I don't think.  (This is documented in lowdown.5.)

**Comment by kristapsdz** [comment]
For **-stms**, I don't understand your reasoning.  The title and author blocks are put into the `TL` and `AU` (etc.) macros, exactly as a regular **ms** roff document.  What do you suggest otherwise?  (The **-stman** equivalent is in the `TH` macro.)

**Comment by kristapsdz** [comment]
Originally for **-tterm**, I included metadata in the output because I figured folks would want to see the document *as they entered it*, only pretty, which includes metadata.  However, I see your point.  Are there any other **-tterm** type of outputs in other markdown tools where metadata is not shown?  I see that pandoc's **-tplain** and **-stplain** follow your suggestion, so I'm inclined to agree with you, but want some additional support.

**Comment by kristapsdz** [comment]
Addressed.  Please re-open this if not.
