### ISSUE TITLE
lacks `uninstall` and `uninstall_libs` targets

### ISSUE THREAD

**Issue by g-branden-robinson** [kristapsdz/lowdown#125]
Following the instructions in _index.md_...

```c
% ./configure
% make
% make regress
# make install install_libs
```

I expected to be able to clean up lowdown after evaluating it, but found that I have to do so by hand.

Please support `uninstall` and `uninstall_libs` targets to undo what `install` and `install_libs` perform.

**Comment by g-branden-robinson** [comment]
Thanks, Kristaps!

**Comment by kristapsdz** [comment]
Hope you enjoy lowdown as much as mandoc! Funny that both of them have similar origin stories. 😆
