### ISSUE TITLE
[Feature request] Add option to control or disable indentation of paragraphs in terminal output

### ISSUE THREAD

**Issue by itshog** [kristapsdz/lowdown#129]
Would it be possible to add a command line option which disables the indentation of normal paragraphs in `-tterm` output? I'm thinking about something like `--term-no-indent` for disabling indentation globally, or `--term-indent=code,lists,paragraphs,tables...` to specify exactly what should be indented if we need more granularity.

My use case for this is using lowdown for previewing markdown files in [vifm](https://github.com/vifm/vifm) (but I guess the same applies for almost every terminal file manager), and having so much empty space between the file list and the preview looks ugly and needlessly shrinks the space for the actual text (I'm attaching a couple of screenshots to show what I mean). I know that I could just pipe the output into `sed 's/^ *//g'` to remove the leading white spaces, but this lacks granularity (it doesn't differentiate between paragraphs, lists, code blocks etc.) and needs an external utility to accomplish something that IMO could be an option in lowdown itself.

Anyway, thanks for the great piece of software!

![20231203_13h18m07s_grim](https://github.com/kristapsdz/lowdown/assets/130040841/f9e358fd-1541-452e-8217-275e24a99450)
![20231203_13h18m09s_grim](https://github.com/kristapsdz/lowdown/assets/130040841/0e93fef8-3c2e-4de5-beee-536c442e7d2f)
![20231203_13h20m21s_grim](https://github.com/kristapsdz/lowdown/assets/130040841/2052c947-2fb6-460a-a76c-4036f46ad44c)
![20231203_13h20m31s_grim](https://github.com/kristapsdz/lowdown/assets/130040841/caec01d1-8248-45d2-b580-6fa244ae3819)

**Comment by WhyNotHugo** [comment]
I'm needing this too. I'm using lowdown to preview files in fzf, but the indentation really breaks things apart.

There's the `--term-hmargin=margin` flag, which defaults to zero, but this value is not respected for paragraphs; paragraphs always have a hardcoded indentation of four.

Should the value of `--term-hmargin` be used instead of the hardcoded value here?

**Comment by kristapsdz** [comment]
Ok, a more elegant fix is in the works.  First, I'm introducing **--term-hpadding**, which does what the default term.h body value did: introduce a left-padding that cuts into the **--term-width**.  It defaults to 4 to preserve existing layouts.  While here, I fixed some off-by-ones for cleaner output and am also clarifying:

```
| columns                                   |
| hmargin | hpadding | ---content--- |      |
          | width                    |      |
```

At some point, I want to introduce RTL capabilities, so this isn't quite future-proof yet, as **--term-hmargin** and **--term-padding** don't affect the right-hand side of the output.
