### ISSUE TITLE
Your personal Mac Homebrew tap

### ISSUE THREAD

**Issue by To1ne** [kristapsdz/lowdown#13]
I've created a tap for Mac Homebrew to install lowdown with `brew install lowdown`. Adding the formula to the official repo was [rejected](https://github.com/Homebrew/homebrew-core/pull/10649) because this project "isn't popular enough".

My tap is over here: https://github.com/To1ne/homebrew-lowdown

But IMHO it makes more sense if you would host the tap under your account. So feel free to fork that repo and take ownership of it (I'll will delete my repo afterward).

**Comment by kristapsdz** [comment]
There's already https://github.com/kristapsdz/homebrew-repo, but thanks!
