### ISSUE TITLE
1.1.0 refuses to build from not detecting strtonum

### ISSUE THREAD

**Issue by 666threesixes666** [kristapsdz/lowdown#134]
hi under funtoo, lowdown 1.0.2 builds fine, but this package is autogenerated for nix.  1.1.0 does not detect strtonum, and throws build time errors because of it.
[lowdownmerge.txt](https://github.com/kristapsdz/lowdown/files/14341677/lowdownmerge.txt)

**Comment by kristapsdz** [comment]
Whatever is compiling lowdown, which seems to be using the dynamic library, must be fixed to include the *compats.o* file in the linking phase.  This file contains a shim for strtonum() amongst other functions.

The reason this doesn't happen in the provided Makefile, which generates lowdown using the static archive in the source tree.
