### ISSUE TITLE
Manual and actual lowdown disagree on `term-all-metadata` flag

### ISSUE THREAD

**Issue by solt87** [kristapsdz/lowdown#136]
Thank you for `lowdown`, it has been my go-to markdown program for years now. :)

The manual says that in standalone term-output mode, the `--term-all-metadata` option
should print all metadata, but `lowdown` doesn't recognise that option. As it
turns out, it is actually `--term-all-meta` in main.c (and in versions.xml).
Whichever is supposed to be the correct form, either the source code or the manual
needs an adjustment.

**Comment by kristapsdz** [comment]
Fixed this by adding CLI support for **--term-all-metadata**, thank you so much!
