### ISSUE TITLE
Gemini output prints smart punctuation characters as "â" (hex codepoint e2)

### ISSUE THREAD

**Issue by rnkn** [kristapsdz/lowdown#137]
Hello!

I know that Gemini support is experimental so I hesitate to raise this, but Gemini output seems to print smart punctuation characters as "â" (hex codepoint e2)
```
$ echo \"---\" | lowdown -Tgemini
???
$ echo \"---\" | lowdown -Tgemini | xxd -p
e2e2e20a
```
This only seems to happen with a subset of UTF-8 characters, as most other characters (including "â") output correctly.

**Comment by kristapsdz** [comment]
This was fixed by a recent pull request and will appear in the upcoming version.  Thank you for the report!

**Comment by rnkn** [comment]
Awesome work, thanks!
