### ISSUE TITLE
Better support for cli diff

### ISSUE THREAD

**Issue by To1ne** [kristapsdz/lowdown#14]
I was trying to utilize `lowdown-diff` for diffing files with git.

I've been configuring things like this:

In my global `~/.gifconfig`:

```conf
[diff "markdown"]
	tool = lowdown

[difftool "lowdown"]
	cmd = "lowdown-diff -Tman $LOCAL $REMOTE | groff -Tascii -man | less"
```

I have in my `.gitattributes`:

```
*.md diff=markdown
```

And I wanted `git diff` just to utilize `lowdown-diff` to build a diff, but that doesn't seem to work.

So I'll need to use `git difftool` instead.

With the config above I can `git difftool -t lowdown README.md`. But that output isn't really as great as the html output is.

**Comment by To1ne** [comment]
Sorry, this is quite a messy issue description. But I've been fighting with this for way to long. And I was hoping you could help me out make this better.

**Comment by kristapsdz** [comment]
You're forgetting the **-s** switch!
