### ISSUE TITLE
Feature request: Option to embed CSS

### ISSUE THREAD

**Issue by carlos22** [kristapsdz/lowdown#142]
Hi this is a really nice tool. 

My problem is I want to publish a standalone HTML file that also works offline and uses some CSS. But I don't want to distribute two files, so it would be great to somehow embed some CSS into the HTML file. Maybe a another meta option to provide a file that is then fetched and put between `<style></style>` tags in the header?

Another Idea would be some kind of partials so having a metadata head that just outputs whatever is in that file into the ´<head></head>` of the html. That way one could also embed js.

What do you think?

**Comment by kristapsdz** [comment]
What do other tools use?
