### ISSUE TITLE
Bad rendering of "horizontal rule" in terminal

### ISSUE THREAD

**Issue by Disonantemus** [kristapsdz/lowdown#147]
When lowdown renders [thematic breaks](https://spec.commonmark.org/0.31.2/#thematic-breaks) in the terminal, should have an empty line previous to the separator (Horizontal rule). Same file, exported to HTML, renders as expected in browser. Next is an example markdown file, rendered in terminal by many CLI tools:

example:
~~~ocaml
$ cat 1.md
1. item 1
1. item 2

---

> Note: this is a note.
~~~

lowdown with terminal output:
~~~ocaml
$ lowdown 1.md -tterm
     1. item 1
     2. item 2
    ~~~~~~~~

      | Note: this is a note.
~~~


pandoc to plain text::
~~~ocaml
$ pandoc 1.md -t plain
1.  item 1
2.  item 2

------------------------------------------------------------------------

  Note: this is a note.
~~~

mdcat:
~~~ocaml
$ mdcat 1.md
 1. item 1
 2. item 2

════════════════════════════════════════════════════════════════════════

    Note: this is a note.
~~~

glow:
~~~ocaml
$ glow 1.md

                                                                        
  1. item 1                                                             
  2. item 2                                                             
                                                                        
  --------                                                              
                                                                        
  │ Note: this is a note. 
~~~

html output from lowdown, rendered by w3m:
~~~ocaml
$ lowdown 1.md | w3m -T text/html -dump -cols 73
 1. item 1
 2. item 2

------------------------------------------------------------------------


    Note: this is a note.
~~~

---

Also tested online with:

- https://daringfireball.net/projects/markdown/dingus
- http://markdown.pioul.fr/
- https://dillinger.io/
- https://stackedit.io/app#
- ... and github

---

Extra: Is possible to change the "Horizontal rule" from tilde to minus or underscore?

**Comment by kristapsdz** [comment]
Very good catch on this.  Beyond the obvious newline being inserted, I'm also changing the characters shown to be proper UTF-8 line-drawing glyphs.  This includes, beyond your example, tables, vertical lines (e.g., blockcode), and footnote rule.  Thanks for pointing this out!
