### ISSUE TITLE
API breakage

### ISSUE THREAD

**Issue by clausecker** [kristapsdz/lowdown#148]
The update to 1.4.0 broke consumers of the library such as gcli.

Please avoid breaking changes to the API.  If you must do them, the major (not minor) version must be increased as per the usual conventions (e.g. as codified by semver).

I see no point in this API change, it just broke stuff for no reason.

**Comment by kristapsdz** [comment]
The release notes state the API changes and the reasons.  Issues like this are why I hate open source.

**Comment by clausecker** [comment]
@kristapsdz I don't get to read the release notes when the distributor of the dependency does what he believes to be a harmless minor version updates.  As per the usual conventions, minor and patch releases must not have breaking changes, only major version updates are allowed to have them.

Yeah I know it's annoying, but it's much easier for everyone to stick to the common conventions and bump the major version on breaking API change.  Or avoid the API change in the first place, it doesn't look like it was really necessary.
