### ISSUE TITLE
Non-conformity with CommonMark p+li case

### ISSUE THREAD

**Issue by step-** [kristapsdz/lowdown#149]
Hi, thank you for making lowdown, and happy holidays.

I found a case where `cmark`'s and `lowdown`'s outputs differ
(versions: cmark 0.31.1, lowdown 1.4.0).

```bash
cmark <<< $'P\n   - LI'
```
output:
```html
<p>P</p>
<ul>
<li>LI</li>
</ul>
```

But

```bash
lowdown -thtml <<< $'P\n   - LI'
```
output:
```html
<p>P
   - LI</p>
```

Note that without the leading P, lowdown follows CommonMark correctly.

```bash
lowdown -thtml <<< $'   - li'
```
output:
```html
<ul>
<li>li</li>
</ul>
```

**Comment by kristapsdz** [comment]
That's expected behaviour: markdown and commonmark don't overlap for many cases.  lowdown's support of commonmark is quite limited, and this isn't one of the features supported: lists are block-scoped and thus need a newline.  I'm happy to merge in changes, but these are really tricky.

**Comment by step-** [comment]
Thank you for explaining your design.
