### ISSUE TITLE
Custom metadata keys

### ISSUE THREAD

**Issue by aminb** [kristapsdz/lowdown#18]
Hi,

I'd like to have an `updatedate` key, similar to `date`, to indicate the date when the post was last updated. It'd be nice if `lowdown` supported custom metadata keys, perhaps possibly with a notion for declaring the "type" of the field's value.

**Comment by kristapsdz** [comment]
I don't really know what you're asking for.  You can have any metadata keys you want, and extract them with **-X**.  Is that what you mean?

**Comment by aminb** [comment]
You're quite right! I just tried, and using arbitrary keywords does seem to work. Reading the man pages, for some reason I'd thought that one could only use the few keywords that were built into lowdown.

Closing.
