### ISSUE TITLE
Download Issue while trying to use lodown package

### ISSUE THREAD

**Issue by mvtomas** [kristapsdz/lowdown#22]
Hi,

I am trying to download PNAD-Contínua using lodown package with the query below:

pnadc_cat <-
  get_catalog( "pnadc" ,
               output_dir = file.path( path.expand( "~" ) , "PNADC" ) )
pnadc_cat <- subset( pnadc_cat , year == 2018 & quarter == '03' )
pnadc_cat <- lodown( "pnadc" , pnadc_cat )

Before the error, R trys 10 times to download and it keeps giving the message as follow:

download issue with
'ftp://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/Documentacao/Dicionario_e_input_20181114.zip'

The error log is this:

Error in httr_filesize(this_url, attempts, sleepsec) : 
  httr::HEAD( 'ftp://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/Documentacao/Dicionario_e_input_20181114.zip' )
failed after 10 attempts
   year quarter interview
26 2018      03      <NA>

When I put this address at google Chrome it download correctly. Do you think that there is something else I might be trying?

**Comment by brunolucian** [comment]
Same problem here, did you solve this?

**Comment by kristapsdz** [comment]
Wrong project.
