### ISSUE TITLE
[Feature proposal] Support for GFM's todo extension

### ISSUE THREAD

**Issue by lochlainn** [kristapsdz/lowdown#27]
Github-flavored markdown has support for todo lists that can be completed:

- [ ] todo item
- [x] completed item

I'd like to add functionality for this. Would it be something you'd want to merge?

**Comment by kristapsdz** [comment]
Absolutely matey.  It's a lot to swallow, though: there's adding it to document.c and lowdown.h, all of the front-ends (latex.c, tree.c, nroff.c, html.c, term.c), and also the manpage bits.

**Comment by kristapsdz** [comment]
Closing this out as it seems to be going nowhere, sadly!
