### ISSUE TITLE
-Tms : quoted strings begin *and* end with 201C

### ISSUE THREAD

**Issue by larrykollar** [kristapsdz/lowdown#29]
U+201C is the left curly quote, and it properly begins a "quoted string" in lowdown's output. However, with -Tms, the end of the quote is also U+201C instead of U+201D. I don't see where this gets rendered in either nroff.c or smartypants.c.

A minimal example:

```
% echo 'He said, "I got no freeking clue," and walked away.' | ./lowdown -Tms
.LP
He said, \[u201C]I got no freeking clue,\[u201C] and walked away.
%
```

Lowdown version from GitHub, running on MacOS 10.15.6.

**Comment by kristapsdz** [comment]
Great catch!  So the comma is being interpreted as an adjacent word break, which resets whether the punctuation to the right is in a new "scope".  (If you move the quote within the comma, it changes.)  I already have a TODO in the code about fixing this---I'll get on it!  Thanks for the note.

**Comment by kristapsdz** [comment]
The last updates should fix this.  Please re-open this if it doesn't!  I've also added a regression suite specifically for smart typography.

**Comment by larrykollar** [comment]
Looks good!
