### ISSUE TITLE
Hard wrap doesn't work right with -Tms

### ISSUE THREAD

**Issue by larrykollar** [kristapsdz/lowdown#30]
Hard wrap (`—nroff-hardwrap`) with `-Tms` puts the `.LP` at the end of the previous line. A minimal example:

```
% echo 'first paragraph that needs to consist of a lot of text to trigger the hardwrap and whatever else there might be.\n\nAnd another paragraph' | ./lowdown -Tms --nroff-hardwrap
.LP
first paragraph that needs to consist of a lot of text to trigger the hardwrap and whatever else there might be..LP
And another paragraph%                                                                                                                                                                         %
```

Ideally, hardwrap with `-Tms` would break lines at the end of each sentence, but I'll accept that it could be harder than it sounds.

Current GitHub source, running on MacOS 10.15.6

**Comment by kristapsdz** [comment]
This seems to have been a holdover from **-Thtml**, which doesn't need line breaks.  This should be fixed, though I personally find the behaviour of all of the `hardwrap` options to be super confusing.  Please re-open if not repaired in your use cases!
