### ISSUE TITLE
Off-by-one error in Base Header Level metadata (with patch)

### ISSUE THREAD

**Issue by larrykollar** [kristapsdz/lowdown#32]
As I understand MultiMarkdown's metadata, setting "Base Header Level: 1" in metadata is a null function. With the current code base, Lowdown increments by the value of Base Header Level. The following example shows the issue:

```
% echo 'title: Big Test\nBase Header Level: 1\n\n# Chapter 1\n\nThis is a test.\n\n## Sub-heading\n\nThis is only a test.' | ./lowdown -Tms -s
.TL
Big Test
.NH 2
.XN Chapter 1
.PP
This is a test.
.NH 3
.XN Sub-heading
.PP
This is only a test.
```

I've attached a patch for nroff, html, and latex that defaults Base Header Level to 1, then accounts for it when setting heading levels.
[basehdr.patch.txt](https://github.com/kristapsdz/lowdown/files/5044499/basehdr.patch.txt)

P.S. I've tested this with nroff output, but not with HTML or LaTeX.

**Comment by kristapsdz** [comment]
Thanks again, Larry!  If the last commit behaves unexpectedly, please reopen this.  The issue should be fixed in all output media except **-Tterm**, which doesn't respect the base header level.  (I guess... it doesn't make sense that it would, as it's meant to format the source.)
