### ISSUE TITLE
Unexpected literal ".PP" in markdown bullets when rendering man page

### ISSUE THREAD

**Issue by step-** [kristapsdz/lowdown#35]
Lowdown 0.7.3 on Linux

Consider the following test case (file test.md):
```markdown
# right
* source
[source](http://source)
* binary
[binary](http://binary)

# wrong
* source
[source](http://source)

* binary
[binary](http://binary)
```
Render man page:

```sh
lowdown -Tman -s test.md
```

Result:

```troff
.SH right
.sp 1.0v
.RS
.ti -\w'\(bu  'u
\(bu  source
\f[I]source\f[R]
.RE
.RS
.ti -\w'\(bu  'u
\(bu  binary
\f[I]binary\f[R]
.RE
.SH wrong
.sp 1.0v
.RS
.ti -\w'\(bu  'u
\(bu  .PP
source
\f[I]source\f[R]
.RE
.sp 1.0v
.RS
.ti -\w'\(bu  'u
\(bu  .PP
binary
\f[I]binary\f[R]
.RE
```

In section "wrong", notice `.PP` after the bullet `\(bu`. This seems wrong and results in the literal text ".PP" being printed in the manual page:

```sh
lowdown -Tman -s | man -l -
```

Result:

```

·  source source
·  binary binary

·  .PP source source

·  .PP binary binary

```

If I delete the last two line and render a manual page again ".PP" isn't added -- correctly.

```markdown
# right
* source
[source](http://source)
* binary
[binary](http://binary)

# wrong
* source
[source](http://source)
```

Result:

```

·  source source
·  binary binary

·  source source

```

With lowdown version 0.4.6 I did not see the stray ".PP" after the bullets. I think that version 0.4.6 outputs `.LP` for paragraphs while the newer versions output `.PP`. Regardless, there were no unexpected ".PP" or ".LP" in the man page.

With `-Thtml` a similar issue surfaces, in the "wrong" section, `<p>` follows `<li>`, which seems wrong.  When rendering the HTML in a browser, the effect isn't necessarily noticeable unlike in a man page, in which ".PP" becomes literal text.

```html
<h1 id="right">right</h1>

<ul>
<li>source
<a href="http://source">source</a></li>
<li>binary
<a href="http://binary">binary</a></li>
</ul>

<h1 id="wrong">wrong</h1>

<ul>
<li><p>source
<a href="http://source">source</a></p></li>
<li><p>binary
<a href="http://binary">binary</a></p></li>
</ul>
```

For comparison, I checked how GitHub renders the same case to HTML, and -- to my surprise -- GitHub behaves like lowdown. For instance, see [this page](https://github.com/step-/scripts-to-go/tree/master/quicklaunch#links) in your browser's developer tools, and compare the HTML code for the single bullet under **2:** and the two bullets under **3:**.  The single bullet doesn't include a `<p>` tag while each of the two bullets does.

**Comment by kristapsdz** [comment]
Thanks for this report!  The weird paragraph creation is stipulated by the original markdown spec---I can't comment on that.  I'll look into the stray PPs though.

**Comment by kristapsdz** [comment]
The last commit fixes this, thank you!  I'll tag out a release tomorrow, so please let me know if this breaks anything else for you.

**Comment by step-** [comment]
Thank you very much.  I can confirm that  8c0a733 fixed this issue in my documents.  I haven't noticed any other issues.
