### ISSUE TITLE
columns in -Tterm aren't space aligned

### ISSUE THREAD

**Issue by qlcom** [kristapsdz/lowdown#36]
given the input (using `-Tterm`)
```
| name    | git repository                        |
| ------- | ------------------------------------- |
| fzf     | https://github.com/junegunn/fzf       |
| lf      | https://github.com/gokcehan/lf        |
| lowdown | https://github.com/kristapsdz/lowdown |
| st      | https://git.suckless.org/st           |
| uni     | https://github.com/arp242/uni         |
```

produces output (control sequences are removed)

```
fzfhttps://github.com/junegunn/fzf
lfhttps://github.com/gokcehan/lf
lowdownhttps://github.com/kristapsdz/lowdown
sthttps://git.suckless.org/st
unihttps://github.com/arp242/uni
```

i expected the columns to be spaces aligned. like,

```
fzf     https://github.com/junegunn/fzf
lf      https://github.com/gokcehan/lf
lowdown https://github.com/kristapsdz/lowdown
st      https://git.suckless.org/st
uni     https://github.com/arp242/uni
```

using `:` to specify alignment doesn't effect the alignment in output.

**Comment by qlcom** [comment]
i think there is no need to have the `Tterm` option.

**Comment by kristapsdz** [comment]
This is a known missing feature.  It's listed at the bottom of https://kristaps.bsd.lv/lowdown under "How Can You Help?"  I'm happy to help if you'd like to take a go at it!

**Comment by qlcom** [comment]
> I'm happy to help if you'd like to take a go at it!

sorry, i can't help on this. I am not good at C.
