### ISSUE TITLE
Problems with inline HTML being wrapped in <p> tags

### ISSUE THREAD

**Issue by e-zk** [kristapsdz/lowdown#37]
I noticed while attempting to convert a Markdown document to HTML that inline HTML is sometimes wrapped in `<p>` tags unnecessarily. For instance, take the input:

```markdown
# Testing

This is a paragraph. 

<details><summary>Click Me</summary>
Pop!
</details>
```

The output, after running `lowdown -s -Thtml --html-no-skiphtml --html-no-escapehtml test.md`:

```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>Untitled article</title>
</head>
<body>

<h1 id="Testing">Testing</h1>

<p>This is a paragraph. </p>

<p><details><summary>Click Me</summary>
Pop!
</details></p>
</body>
</html>
```

The `<details>` tag is wrapped in a `<p>` block. While most browsers can figure this out and display it fine, according to https://html5.validator.nu/ and https://validator.w3.org/ this is not valid HTML because:

> ```
> Error: No p element in scope but a p end tag seen.
>
> From line 16, column 11; to line 16, column 14
>
> </details></p>↩</bod
> ```

The issue just gets worse if I put tags on their own separate lines; each tag gets wrapped in `<p>`.

**Comment by kristapsdz** [comment]
Thank you!  Do other standard Markdown formatters do this or not?

In the original markdown (or rather, in hoedown as lowdown originally forked), top-level blocks are checked and not wrapped.  We check this in hhtml_find_block(), html.c, just like in the original.  The way to solve this is to look through the HTML5 standard and see if there are any additional block-level elements that need to be added, then add them to the list of elements therein.  Can you do this?

**Comment by e-zk** [comment]
You mean hhtml_find_block(), in document.c? Sounds simple enough.

> The way to solve this is to look through the HTML5 standard and see if there are any additional block-level elements that need to be added, then add them to the list of elements therein.

Just for the record I'll be using this to add to the block-level elements: https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements.

> Can you do this?

Sure can!

**Comment by kristapsdz** [comment]
Thanks, fixed with the last commit, and will make its way into the next release!
