### ISSUE TITLE
Other sections for -s -Tman?

### ISSUE THREAD

**Issue by paravoid** [kristapsdz/lowdown#43]
OK, I know this is probably going to sound like heresy ;) and would understand if you were to decline this, but I was wondering how open you would be at allowing other sections for the manpage standalone output.

I'm cognizant of the footnote on the homepage (_"You may be tempted to write manpages in Markdown, but please don't: use mdoc(7), instead"_), but there are projects that do have their documentation in Markdown out there today and then use tools like pandoc and ronn to convert their Markdown to e.g. section 1 or 3 manpages.

It would be neat if lowdown could be an alternative to them :)

**Comment by kristapsdz** [comment]
Shouldn't be too hard to write a patch that recognises the "Man Section" metadata and uses that instead of section 7.  Please note the little "How Can You Help" bits on the webpage that relate to improvements that may be made to **-Tms** and **-Tman** output... ;)
