### ISSUE TITLE
Odd indentation in definition list with -Tman

### ISSUE THREAD

**Issue by paravoid** [kristapsdz/lowdown#48]
Not sure this is actually related to definition lists, this may be a generic indentation problem.

I'm trying to parse the [mmdblookup manual page](https://raw.githubusercontent.com/maxmind/libmaxminddb/master/doc/mmdblookup.md), from the libmaxminddb project.

This excerpt:
```
This application accepts the following options:

-f, --file

:    The path to the MMDB file. Required.

-i, --ip

:    The IP address to look up. Required.

-v, --verbose

:    Turns on verbose output. Specifically, this causes this
     application to output the database metadata.

--version

:    Print the program's version number and exit.

-h, -?, --help

:    Show usage information.
```

Seems to be misparsed. The mandoc/groff output is:
```
   -f, --file
              The path to the MMDB file. Required.

     -i, --ip
              The IP address to look up. Required.

-v, --verbose
              Turns on verbose output. Specifically, this causes this
               application to output the database metadata.

    --version
              Print the program's version number and exit.

-h, -?, --help
              Show usage information.

```

It seems there are a bunch of e.g. `.ti -\w'-f, --file 'u`, which I don't really understand. Why would we de-indent based on the length of the line above? Anyway, I'm beyond my depth here, so leaving it to you :)

The -Thtml output looks OK. The -Tterm output… crashes, due to both #47, and I think another underlying bug...

**Comment by kristapsdz** [comment]
Ok, I've done some significant rooting around in **-Tman**/**-Tms** for this to work.  Can you please check it out?  Now nested lists of all types (ordered, unordered, definition) should all Just Work.  While here, I've also done other cleanup work as noted at the last block of [the version notes](https://github.com/kristapsdz/lowdown/blob/master/versions.xml).

**Comment by paravoid** [comment]
Wow, thanks so much! I'm glad I didn't make an attempt to fix this myself 😄

The definition lists look great now! Couple of points:
- The `-Tterm` output for def lists includes the colon. Is that intended? It looks odd, but it also looks like it was parsed (it's yellow), so maybe that is intentional?
- Bullets (e.g. `* foo\n* bar\n`) seem to be translated to `.IP` without an indentation specified. Groff and mandoc default to 7n, which feels… ugly. Pandoc translates them to `.IP \bu 2` instead. I realize that's more of a preference and not a bug, though :)

**Comment by kristapsdz** [comment]
I merged the `bu` suggestion, thanks!  And the **-Tterm** output is intentional, yes.  If you think there's a more intuitive way to present this, then by all means draw up a patch---**-Tterm** is def open to creative thinking.  Eventually I'd like to have **-Tterm** output configurable, or at least have an un-colourised variant, but that's a different story.  Meanwhile, I'm going to let the the **-Tman** and **-Tms** code sit in AFL for a few cycles, then tag out a release assuming it doesn't find anything.   I'm closing out this issue as fixed.   Thanks again!
