### ISSUE TITLE
Support metadata definition in command line arguments

### ISSUE THREAD

**Issue by ericonr** [kristapsdz/lowdown#49]
Hi! In Void Linux we make heavy usage of markdown for our https://github.com/void-linux/void-docs project. Since last year we have a `void-docs` package which ships the generated HTML from mdbook, together with the markdown sources and mandoc converted by pandoc.

Regarding specifically the markdown -> mandoc conversion, I'd like to switch from pandoc to lowdown, if at all possible. However, this requires some changes, since we currently pass information such as page title and section in the pandoc command line (https://github.com/void-linux/void-docs/blob/58f2e4d95aa9110301db9dde2cccabd568731011/res/build.sh#L22). I'd also like to avoid including the metadata supported by lowdown in each and every file. Therefore, I'd like to know if there's interest in supporting a `--metadata` or similar command line flag, which would allow me to define these values in the lowdown command line like `--metadata title="something"`. If you think that's a feature you'd like to have, I can definitely work on it. Just want to be sure a PR to this effect has chances of being accepted.

Furthermore, would a `header` metadata entry, like the one supported by pandoc, and which creates a title line like `.TH "SUMMARY" "7" "" "" "Void Docs"` (for `header="Void Docs"`), be accepted?

On a side note, I'm glad to have found `lowdown`. The term output allows me to depend only on C instead of a Rust program (we are currently using mdcat to display markdown in the terminal) :)

**Comment by kristapsdz** [comment]
Yes to both counts.  For the **--metadata**, please have both **-m** and **-M**, where the former *will not* override document metadata and the latter *will*.  The latter is consistent with pandoc.  Just put a `lowdown_metaq` (or two, one for **-m**, another for **-M**) in `lowdown_opts`.

**Comment by ericonr** [comment]
How "defined" would you say behavior is if a document has multiple metadata entries with the same key? As in, do I have to care about having "robust" behavior in such cases?

From what I can tell, the title that will be applied to a man page is the last one in the metadata queue:

```
	TAILQ_FOREACH(m, mq, entries)
		if (strcasecmp(m->key, "author") == 0)
			author = m->value;
		else if (strcasecmp(m->key, "copyright") == 0)
			copy = m->value;
		else if (strcasecmp(m->key, "affiliation") == 0)
			affil = m->value;
		else if (strcasecmp(m->key, "date") == 0)
			date = m->value;
		else if (strcasecmp(m->key, "rcsauthor") == 0)
			rcsauthor = rcsauthor2str(m->value);
		else if (strcasecmp(m->key, "rcsdate") == 0)
			rcsdate = rcsdate2str(m->value);
		else if (strcasecmp(m->key, "title") == 0)
			title = m->value;
		else if (strcasecmp(m->key, "section") == 0)
			section = m->value;
```

but the title printed with `-X title` will be the first one in the queue:

```
		TAILQ_FOREACH(m, &mq, entries) 
			if (strcasecmp(m->key, extract) == 0)
				break;
		if (m != NULL) {
			fprintf(fout, "%s\n", m->value);
		} else {
			status = EXIT_FAILURE;
			warnx("%s: unknown keyword", extract);
		}
```

I'm asking because I don't know if I should try to deal with such cases. I'm currently `TAILQ_REMOVE`ing a value from the metadata queue I fill up for `-m` and `-M` after I've used it to replace the value from the document, but this means that if a document has another entry with the same key, I won't override it in the new case.
