### ISSUE TITLE
Single quotes at the beginning of line are not escaped

### ISSUE THREAD

**Issue by paravoid** [kristapsdz/lowdown#54]
OK, this is a good one -- you can't make these things up!

The [libmaxminddb man page](https://raw.githubusercontent.com/maxmind/libmaxminddb/main/doc/libmaxminddb.md) has this excerpt (line wrappings intact):
```markdown
This function will work with IPv4 addresses even when the database contains
data for both IPv4 and IPv6 addresses. The IPv4 address will be looked up as
'::xxx.xxx.xxx.xxx' rather than being remapped to the `::ffff:xxx.xxx.xxx.xxx`
block allocated for IPv4-mapped IPv6 addresses.
```

With lowdown 0.8.0 and -Tman, this results into an almost identical output (only ``` escaped).

But, this means that we now have the token `'::xxx.xxx.xxx.xxx' `, at the beginning of a line, which groff interprets as a macro, hiding it from the output, and emitting a warning (`warning: macro '::xxx.xxx.xxx.xxx'' not defined`)

**Comment by kristapsdz** [comment]
Can you confirm that you're running with **--nroff-no-smarty**?  When I run this same manpage through **-Tman** in the current version, I get:

```
This function will work with IPv4 addresses even when the database contains
data for both IPv4 and IPv6 addresses. The IPv4 address will be looked up as
\[u2018]::xxx.xxx.xxx.xxx\[u2019] rather than being remapped to the \fC::ffff:xxx.xxx.xxx.xxx\fR
block allocated for IPv4-mapped IPv6 addresses.
```

**Comment by paravoid** [comment]
I guess you figured it out in the meantime, but indeed, I forgot to mention that I was using `--out-no-smarty -s -Tman` - apologies!
