### ISSUE TITLE
distclean leaves *.old files behind

### ISSUE THREAD

**Issue by paravoid** [kristapsdz/lowdown#55]
OK, this is really really minor but:
```shell
$ ./configure
$ ./configure
$ make
$ make distclean
```

This leaves behind `config.h.old` and `config.log.old`, generated by the second `./configure` invocation.

Fix:
```diff
diff --git a/Makefile b/Makefile
index da8f656..e86f58d 100644
--- a/Makefile
+++ b/Makefile
@@ -252,7 +252,7 @@ clean:
        rm -f index.latex.aux index.latex.latex index.latex.log index.latex.out
 
 distclean: clean
-       rm -f Makefile.configure config.h config.log
+       rm -f Makefile.configure config.h config.log config.h.old config.log.old
 
 regress: lowdown
        tmp1=`mktemp` ; \
```

**Comment by paravoid** [comment]
In the same spirit, somewhat separate issue but also so minor that probably not worth a separate bug for :)

`make distclean` is not idempotent; it removes `Makefile.configure`, which the Makefile has an include for, so in the second invocation the `include` fails. Changing the `include` to a `-include` (or `sinclude` as that is apparently more portable?) fixes the issues with seemingly no ill effects for other targets (but I haven't tested them all).

**Comment by kristapsdz** [comment]
That's correct behaviour: `make distclean` is supposed to set you back to before running `./configure`.  The *Makefile* needs *Makefile.configure* intentionally to set all of its required flags: it means that `./configure` has been run.  I will remove the *.old* files, though.
