### ISSUE TITLE
Regression in printing tables between 0.7.9 and master

### ISSUE THREAD

**Issue by ericonr** [kristapsdz/lowdown#56]
I was unable to git bisect this, because a few commits were simply not printing anything.

From the following markdown:

```
# Mirrors

| Repository                                     | Location         |
|------------------------------------------------|------------------|
| https://alpha.de.repo.voidlinux.org/         | EU: Finland      |
| <https://mirrors.servercentral.com/voidlinux/> | USA: Chicago     |
| <https://alpha.us.repo.voidlinux.org/>         | USA: Kansas City |
| <https://mirror.clarkson.edu/voidlinux/>       | USA: New York    |
```

Using `./lowdown -s -Tman mirrors.md`; with `-Tms` on master it's broken in the same way, and on 0.7.9 it's broken in a weirder way still.

With lowdown 0.7.9, I get:

```
.TH "Untitled article" 7
.SH Mirrors
.TS
tab(|) expand allbox;
lb lb
l l.
T{
Repository
T}|T{
Location
T}
T{
\f[I]https://alpha.de.repo.voidlinux.org/\f[R]

T}|T{
EU: Finland
T}
T{
\f[I]https://mirrors.servercentral.com/voidlinux/\f[R]

T}|T{
USA: Chicago
T}
T{
\f[I]https://alpha.us.repo.voidlinux.org/\f[R]

T}|T{
USA: Kansas City
T}
T{
\f[I]https://mirror.clarkson.edu/voidlinux/\f[R]

T}|T{
USA: New York
T}
.TE
```

and with lowdown from master, I get:

```
.\" -*- mode: troff; coding: utf-8 -*-
.TH "Untitled article" "7" ""
.SH Mirrors
.TS
tab(|) expand allbox;
lb lb
l l.
T{
Repository
T}
|
T{
Location
T}
T{
\fIhttps://alpha.de.repo.voidlinux.org/\fR
T}
|
T{
EU: Finland
T}
T{
\fIhttps://mirrors.servercentral.com/voidlinux/\fR
T}
|
T{
USA: Chicago
T}
T{
\fIhttps://alpha.us.repo.voidlinux.org/\fR
T}
|
T{
USA: Kansas City
T}
T{
\fIhttps://mirror.clarkson.edu/voidlinux/\fR
T}
|
T{
USA: New York
T}
.TE
```

With the first one, I get a normal looking table without any issues, but the latter generates a completely broken table (I'm displaying them with `mandoc(1)`).

**Comment by kristapsdz** [comment]
Great find!  In the first example (with old *lowdown*), it's just luck that it works: blank lines in the output are the reason I re-wrote the serialisation algorithm to be two-pass.  And as you can see, this is mostly due to links.

The referenced patch fixes this.  Tested in a variety of situations with embedded links, links in styles, etc.

If you can confirm this fix, please close the issue.  Thank you for reporting!

**Comment by ericonr** [comment]
The `-Tman` output now looks fine, but the `-Tms` output is quite broken still... Do you want to repurpose this issue for that?

```
┌─────────────────────────────────────┬──────────────────┐
│Repository                           │ Location         │
├─────────────────────────────────────┼──────────────────┤
│W -D                                 │ EU: Finland      │
│https://alpha.de.repo.voidlinux.org/ │                  │
│https://alpha.de.repo.voiseems quite dlinux.org/ │                  │
├─────────────────────────────────────┼──────────────────┤
│                                     │ USA: Chicago     │
├─────────────────────────────────────┼──────────────────┤
│                                     │ USA: Kansas City │
├─────────────────────────────────────┼──────────────────┤
│                                     │ USA: New York    │
└─────────────────────────────────────┴──────────────────┘
```

Thanks for the quick fix!

**Comment by kristapsdz** [comment]
I can't replicate this.   What are the exact commands you're using, and what version of groff?

**Comment by ericonr** [comment]
You'll see an edit above, I had accidentally typed a bit inside the code block.

I'm running `./lowdown -s -Tms mirrors.md |mandoc`, with `mandoc` 1.14.5.

**Comment by kristapsdz** [comment]
That's the problem---mandoc doesn't accept **ms** macros, only **man**.

**Comment by ericonr** [comment]
Ok, sorry for the confusion. Should be all good now, thank you very much :)
