### ISSUE TITLE
Gemini output isn't completely documented in lowdown.1 and prints metadata at the top of the file.

### ISSUE THREAD

**Issue by ericonr** [kristapsdz/lowdown#57]
`-Tgemini` isn't mentioned in `Output modes` of `lowdown(1)`.

Furthermore, using markdown files with metadata information, the metadata gets printed to the resulting gemtext, with no option to disable this. I'm ok with it being either on or off by default, but it would be nice to be able to strip out the metadata.

**Comment by kristapsdz** [comment]
Yes, it's experimental---I don't use Gemini, and I don't know what folks expect.  Is it natural in this case to have **-s** print the metadata and have it suppressed otherwise?

**Comment by snan** [comment]
Yes, by default it should be supressed. Thank you.

**Comment by ericonr** [comment]
If you feel repurposing the `-s` switch for this is fine, I think that's a reasonable course of action. It does feel a bit different from what the switch does for other output formats, but I think that's bike shedding on my part.

**Comment by kristapsdz** [comment]
On second thought, I agree and have committed with **--gemini-markdown** for this purpose.  I've also documented the bits requested.  If this works for you, please close out the issue.

I'd really appreciate input from **-Tgemini** users on issues like (e.g.) nested blockquotes and such.  There's a lot of format conflict between markdown and gemini, in this regard!

**Comment by snan** [comment]
Please change

```
>> this nested blockquote
> this normal blockquote
```

to
```
> this nested blockquote this normal blockquote
```

Thank you.

**Comment by snan** [comment]
I'm not so sure about my last comment.

But, regardless, please change

```
> this first line of a multi-line blockquote
> this second line of a multi-line blockquote
```

to

```
> this first line of a multi-line blockquote this second line of a multi-line blockquote
```

and

```
> this first line of a multi-line blockquote but with two spaces after  
> this second line of a multi-line blockquote
```

to 

```
> this first line of a multi-line blockquote but with two spaces after
> this second line of a multi-line blockquote
```

and keep

```
> this first line of a multi-line blockquote but with an empty line after
>
> this second line of a multi-line blockquote
```

the same.

**Comment by kristapsdz** [comment]
@snan Can you please create a new issue for these so that @ericonr can close this one out if it fixes the original issue?

**Comment by snan** [comment]
Also please change

```
#### Level four, five or lower header
````

to a plain text line

```
Level four, five or lower header
````

(The intent is to split up documents that have many levels of heading into sub-documents of no more than three header-level each. We don't accidentally want to create a formatting that people will abuse for bold text that isn't semantically a header.)

**Comment by snan** [comment]
I will. Thank you @kristapsdz

**Comment by ericonr** [comment]
Works perfectly, thank you very much :)

It might be interesting at some point to study the resulting order of metadata:

```
$ ./lowdown --gemini-metadata -Tgemini diff.md |head
javascript: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js     diff.js
author: Kristaps Dzonsons
affiliation: BSD.lv
rcsdate: $Date$
title: Lowdown Diffing Engine
css: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css     https://fonts.googleapis.com/css?family=Alegreya+Sans:400,400italic,500,700     diff.css

# Lowdown Diffing Engine
```

vs 

```
$ ./lowdown --gemini-metadata -Tgemini -M "title: test" diff.md |head
javascript: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js     diff.js
author: Kristaps Dzonsons
affiliation: BSD.lv 
rcsdate: $Date$
css: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css     https://fonts.googleapis.com/css?family=Alegreya+Sans:400,400italic,500,700     diff.css
title: test

# Lowdown Diffing Engine
``` 

But I don't think it's a concern right now.

**Comment by kristapsdz** [comment]
Easily explained: the metadata is printed as it appears first with **-m**, then the document, then **-M**, with prior invocations removed.  So the `title` moves because its first instance is removed.  (I.e., it's not replaced, it's removed with the new one being added afresh.)
