### ISSUE TITLE
Gemini semantics

### ISSUE THREAD

**Issue by snan** [kristapsdz/lowdown#58]
As requested, and this is me spouting off before having tried your app
so some of these might already be implemented…

Also, Gemini is plain text. It's possible to write a legal Gemini document that looks like this:

```
##### Hello

>> I wrote
> Then you wrote
```

and that will be interpreted as:

A level three header line that reads "# Hello"
and two quote lines, one of which starts with an >.

That's technically legal.

However, let's aim for a more strict and beautiful Gemini text.

## Text lines

Please change

```
Line one
Line two
```

to

```
Line one Line two
```

Please change (note the spaces)

```
Line one  
Line two
```

to
```
Line one
Line two
```

Please keep

```
Line one

Line two
```

the same.

## Link lines

For inline links, do not put footnotes, numbers, or other markers in the text itself.

Instead, please change:

```
Some text with [a link](url) in the middle of it.
```

to

```
Some text with a link in the middle of it.

=> url a link
```

The correct placement for all accumulated links that have been "extracted" in such a way, is which ever comes first out of:

- Just before the next non-"extracted" link (i.e. a link from a list or stand-alone `<p>`, see below)
- Just before the next header
- Just before the end of the document

Do not do "extract" links that already are alone on their line (i.e.
alone in a `<p>`, or, in a very short `<p>`), or that are in a list.

For those, please change

```
- some [link](url) in a list
- [some other link in a list](url)
```

to

```
=> url some link in a list
=> url some other link in a list
```

for lists. Both `<p><a></p>` and `<li><a></li>` should be
turned into link lines without blank lines in between.

```
* also, this is
=> url completely fine
=> url even good, idiomatic
* in gemini
```

In general, gemini text needs way fewer blank lines than markdown needs. In gemini, each line can be parsed as its own thing without being affected by preceding or following lines.

However, please be consistent on whether or not header lines are preceded by a blank line.

### Links before quotes

The following is implied by what I wrote re short `<p>` but just to be explicit:

Please change

```
[My friend](url) wrote:
> some stuff to me
```

to

```
=> url My friend wrote:
> some stuff to me
```

### Reference links

Please change

```
Reference [links][a] come with their own ideal placement.

[a]: /such-as-this-one/
```

to

```
Reference links come with their own ideal placement.

=> /such-as-this-one/ links
```

if possible. I haven't implemented that myself yet but it would be sweet.♥

## Pre-lines (triple-backticks)

Please add an alt text such as "Preformatted text" or "Code".

## List lines

Remember that Gemini does not have `-` for lists, only `*`.

Also Gemini can not nest lists.

Not sure whether it's best to flatten trees or to split sublists out
to be lists of their own.

## Headers

Gemini documents only have three levels of header.

The intent is to split up documents that have many levels of heading
into sub-documents of no more than three header-level each. We don't
accidentally want to create a formatting that people will use for bold
text that isn't semantically a header.

Therefore, please change

```
#### Level four, five or lower header
```

to a plain text line

```
Level four, five or lower header
```

## Blockquote

Please change

```
>> this nested blockquote
> this normal blockquote
```

to
```
> this nested blockquote this normal blockquote
```

But, regardless, please change

```
> this first line of a multi-line blockquote
> this second line of a multi-line blockquote
```

to

```
> this first line of a multi-line blockquote this second line of a multi-line blockquote
```

and

```
> this first line of a multi-line blockquote but with two spaces after  
> this second line of a multi-line blockquote
```

to

```
> this first line of a multi-line blockquote but with two spaces after
> this second line of a multi-line blockquote
```

and keep

```
> this first line of a multi-line blockquote but with an empty line after
>
> this second line of a multi-line blockquote
```

the same.

## Emphasis and similar

Please remove emphasis by turning

```
A line with an *asterisked word* in it
```

into

```
A line with an asterisked word in it
```

But don't change `4 * 4 = 16` to `4 4 = 16`.

Thank you.

I'm subscribed to this thread in case you need clarifications. I'm on a CET timezone though.

**Comment by kristapsdz** [comment]
This space is for issues with lowdown and in this case **-Tgemini**, not general remarks on Gemini.  If you have specific issue with **-Tgemini** output and lowdown, please file them!  If your filing relates to idiomatic Gemini usage, please cite areas of the specification or community consensus when doing so.

**Comment by snan** [comment]
It's fine that this issue got closed, but I interpreted you as asking me to do exactly this—file an issue with this kind of stuff.

I had also sent the text to other community members (and asked them to chime in this thread if they disagreed) and so far I've received positive feedback from them.

**Comment by paper42** [comment]
> ## Headers
> Gemini documents only have three levels of header.
> 
> The intent is to split up documents that have many levels of heading
> into sub-documents of no more than three header-level each. We don't
> accidentally want to create a formatting that people will use for bold
> text that isn't semantically a header.
> 
> Therefore, please change
> 
> ```
> #### Level four, five or lower header
> ```
> 
> to a plain text line
> 
> ```
> Level four, five or lower header
> ```

I don't think this is the best way to solve this, at least a warning should be printed when this happens. And maybe, replacing it with level 3 header would be better.

> ## Emphasis and similar
> Please remove emphasis by turning
> 
> ```
> A line with an *asterisked word* in it
> ```
> 
> into
> 
> ```
> A line with an asterisked word in it
> ```
> 
> But don't change `4 * 4 = 16` to `4 4 = 16`.

This seems to be already implemented, but I don't think it is a good idea. Gemini doesn't have bold or italics, but stripping it is be problematic. For example, how should lowdown know if 4*4*4 is meant to be stripped or not? I think leaving it in the text as it is should be fine.

**Comment by snan** [comment]
Re the `4*4*4` question that was deleted. Lowdown currently interprets that as `4<em>4</em>4` as does Gruber's markdown, pandoc, and and kramdown. In gemtext, it should become `444` by default but with an option to keep it as `4*4*4`. It's specifically for mathematical text that I want the option (although they should really be using `4\*4\*4` if they want `4*4*4`, which lowdown already supports.

**Comment by paper42** [comment]
Yes, I realised this when I posted the reply, that's why I removed it :)
