### ISSUE TITLE
Link conversion for gemini should not have "references" label

### ISSUE THREAD

**Issue by thexhr** [kristapsdz/lowdown#59]
Hi,

when I convert from markdown to gemini, link conversion uses references. Input markdown:

```
[description of the link](https://example.com/link/blub)
```

turns into

```
description of the link[Reference: link-1]

=> https://example.com/link/blub [Reference: link-1]
```

This could be simplified to

```
description of the link

=> https://example.com/link/blub
```

or if a reference is wanted to 

```
description of the link [1]

=> https://example.com/link/blub [1]
```

**Comment by kristapsdz** [comment]
By default, I'm thinking the `[NN]` format is clearest, which no formatting being an option (e.g., **--gemini-no-linkref**).  However, the `[NN]` format is already taken by footnotes.  An option is using alpha instead of simply numbers to differentiate between the two, so `[a]` til `[z]`, then `[aa]`, etc.  Remembering that with **--gemini-link-end** there may be quite a lot of links.  What does the community usually end up doing here?

**Comment by thexhr** [comment]
Most gemini pages I've seen so far, have the links after the block element and not at the end. I assume exactly for your mentioned reason that there may be quite a lot of links.

**Comment by kristapsdz** [comment]
This has taken a bit of time, but I've changed the default behaviour to print lower-case hexavigesimal ("Excel" style) link labels by default instead of regular numbers.  This differentiates from footnotes, which use regular numbers.  I also provided **--gemini-link-roman** to use lower-case roman numerals instead and **--gemini-link-noref** to not print labels at all.  If this works, I'll tag out a release.  Thoughts?

**Comment by thexhr** [comment]
I tested all three options here and they work as expected. I prefer letters over roman numerals since they could get quite long if you have a lot of links and I am not sure if everybody knows them. Since roman numerals are not the default and this is my subjective view, fine with me.

I attached a screenshot on how this looks live when viewed with the Lagrange browser.

![2021-02-19-114036_1011x234_scrot](https://user-images.githubusercontent.com/4893946/108494103-72704f80-72a7-11eb-8cb5-10deef3236f2.png)

**Comment by kristapsdz** [comment]
Nice!  Another option---we can really do what we want, as this is uncharted territory---is to invert this and have footnotes use alpha/roman and links use numbers.  The reasoning is that links are more common than footnotes.  (This refers to default behaviour: there can be options for all of them.)

**Comment by thexhr** [comment]
Would the following be possible (as an option)?

`[description of the link](https://example.com/link/blub)`

turns into

[ ... surrounding text ... ] description of the link [ ... surrounding text ... ] 

`
=> https://example.com/link/blub description of the link`

So that you have no reference at all in the text and just repeat the link's description after the paragraph.

**Comment by kristapsdz** [comment]
That doesn't really work in the case of embedded links, which is why I use labels in the first place.

**Comment by thexhr** [comment]
Not really sure if I understand you correctly. Gemini has no embedded links in a paragraph of text. All links start on a new line prefixed with =>

**Comment by kristapsdz** [comment]
I mean that in Markdown, you can have embedded links like

```
[[hello](www.foo.com)](www.bar.com)
```

In this example, **-Tgemini** currently renders as `hello[a][b]`, where the link text `[a]` points to foo, `[b]` to bar.   If we were showing content, it would be

```
=> www.foo.com hello
=> www.bar.com hello
```

This is just confusing to me, but maybe this makes Gemini sense?

Is there any sort of community consensus on issues like this?  It must have been discussed somewhere at some point...

**Comment by thexhr** [comment]
Thanks for the explanation. I used your example Markdown above to generate HTML using lowdown and tested it in Firefox. You see "hello" as text and the anchor points to foo.com. bar.com is ignored and even marked as invalid in Firefox's source view. So, I personally would not use it :)

For Gemini, I would suggest to go with the above approach of providing two links for such corner cases. If this really confuses someone, they can still raise an issue here and others would have the benefit of Gemini links with content and not with references.

**Comment by kristapsdz** [comment]
I'm just closing out this issue for lack of any consensus.  Please post diffs if you feel strongly about a particular style!
