### ISSUE TITLE
css metadata field doesn't allow specifying multiple files as stated in man page

### ISSUE THREAD

**Issue by sternenseemann** [kristapsdz/lowdown#69]
`lowdown(1)` states

<https://github.com/kristapsdz/lowdown/blob/b4483d0ef85990f54b864158ab786b4a5b3904fa/man/lowdown.1#L406-L407>

but the actual rendering code doesn't seem to implement such a splitting logic:

<https://github.com/kristapsdz/lowdown/blob/b4483d0ef85990f54b864158ab786b4a5b3904fa/html.c#L1052-L1053>

<https://github.com/kristapsdz/lowdown/blob/b4483d0ef85990f54b864158ab786b4a5b3904fa/html.c#L1088-L1089>

Maybe I'm misreading the documentaton, it probably should be clarified.

**Comment by kristapsdz** [comment]
Please include an example where this doesn't work in a markdown file and I'll fix it, thanks.

**Comment by sternenseemann** [comment]
```console
$ cat test.md
css: /css/normalize.css
/css/main.css

Hello World.
$ lowdown -s test.md
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" href="&#47;css&#47;normalize.css
&#47;css&#47;main.css" />
<title>Untitled article</title>
</head>
<body>

<p>Hello World.</p>
</body>
</html>
```

If I understand the man page correctly, this should create two different `<link rel="stylesheet">` tags, right?

**Comment by kristapsdz** [comment]
Ok, I see it!  Seems that the current code requires two or more white-space (space, newlines, etc.) to trigger the multiple-file clause.  I'll fix this and add regression tests, thanks!

**Comment by kristapsdz** [comment]
This same example has uncovered another wrong behaviour where forward slashes are being passed as escaped (see the &#47; above).  I'll look over the encoding to make sure URLs are being properly formed here.
