### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by echkourine25** [kristapsdz/lowdown#70]
How can i put a link to another website or put an image in lowdown ? I'm using article1.md to write retro blog.

Thank you.

**Comment by kristapsdz** [comment]
Are you asking how to put links or images in markdown?

**Comment by echkourine25** [comment]
No, i'm using sblg and had to write some article in article*.md instead of article*.xml i tried to use markdown but failed.

**Comment by kristapsdz** [comment]
I'm sorry, I don't really understand the problem you're having.  Can you lay out a step by step in what you're doing, and where the problem lies, with examples from your system if possible?
