### ISSUE TITLE
term output doesn't indent lists enough

### ISSUE THREAD

**Issue by edolstra** [kristapsdz/lowdown#73]
For example, given the following input:

```markdown
bla

* foo

  bar

bla
```

`lowdown -Tterm` produces the following output:

```
    bla

  - foo

    bar

    bla
```

So it's not clear that `bar` is a paragraph in a list item rather than at top-level. I think it would be better to indent lists a bit more, e.g.

```
    bla

    - foo

      bar

    bla
```

Alternatively, maybe top-level paragraphs shouldn't be indented at all.

P.S. thank you for lowdown! We're using it in the Nix project for rendering Markdown docs in the repl and for command line help.

**Comment by kristapsdz** [comment]
If the last commit makes this better, let me know and I'll tag a release with it.

If you'd like to do more styling, don't hesitate to submit patches directly to term.c!

**Comment by edolstra** [comment]
Thanks, it works great!
