### ISSUE TITLE
Prefix is not rendered when body is empty

### ISSUE THREAD

**Issue by kanashimia** [kristapsdz/lowdown#75]
This:
```
> This is the first level of quoting.
>
> > This is nested blockquote.
>
> Back to the first level.
```

Results in this:
```
    | This is the first level of quoting.

    |     | This is nested blockquote.

    | Back to the first level.
```

But should in this:
```
    | This is the first level of quoting.
    |
    |     | This is nested blockquote.
    |
    | Back to the first level.
```

**Comment by kristapsdz** [comment]
Can you check the commit above with any samples pages you have handy?  So far I don't see any fall-out with several complex examples, but it's a pretty significant change (if not many lines of code).

**Comment by kanashimia** [comment]
Oh nevermind, second issue seems to not be caused by this change, rather it was all wrong all along xD
It is an parsing error, AST is wrong.

**Comment by kristapsdz** [comment]
>... It is an parsing error, AST is wrong.

The other markdown parsers I could find rendered this is a one blockquote with two paragraphs, just like lowdown.

**Comment by kanashimia** [comment]
> > ... It is an parsing error, AST is wrong.
> 
> The other markdown parsers I could find rendered this is a one blockquote with two paragraphs, just like lowdown.

Well i've linked https://commonmark.org, that one surely must be up to the spec right? 

Also there is a spec on that site, and it is very helpful:
> A document cannot contain two block quotes in a row unless there is a blank line between them.

**Comment by kanashimia** [comment]
Oh, well idk, if one were to follow all of the commonmark spec, then it could be much easier to just paste all of the stuff listed there as tests, otherwise you have to pick and choose between different behaviours. 

I've tested `glow`, and it parses it as two separate blocks, it just makes more sense for me, but then you are up to decide.
