### ISSUE TITLE
-Tmd: a built in markdown formatter

### ISSUE THREAD

**Issue by daeluk** [kristapsdz/lowdown#77]
Could `lowdown` in theory output well-formatted markdown when given valid, but not-so-well-formatted
markdown as input?

Since `lowdown` generates an AST this (to my untrained eyes) seems to be a cool feature that could be added by writing a markdown renderer.

I know other tools exist, like [markdownfmt](https://github.com/shurcooL/markdownfmt) and I believe `pandoc` can do this, but having this ability in `lowdown` would remove the need for those.

I would be curious about your thoughts regarding this.

**Comment by kristapsdz** [comment]
Hi daeluk, I don't see the point.  But if you'd like to write and maintain it, I'll help however I can!
