### ISSUE TITLE
Bew Install Lowdown error on Mac

### ISSUE THREAD

**Issue by vulcasian** [kristapsdz/lowdown#8]
Tried to do a Brew Install Lowdown on a Mac OS Sierra (v. 10.12.5)

This was the error message:

Last 15 lines from /Users/Huckleberry/Library/Logs/Homebrew/lowdown/02.make:
cc -g -W -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter   -c -o compat_progname.o compat_progname.c
cc -g -W -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter   -c -o compat_reallocarray.o compat_reallocarray.c
cc -g -W -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter   -c -o compat_strlcat.o compat_strlcat.c
cc -g -W -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter   -c -o compat_strlcpy.o compat_strlcpy.c
cc -g -W -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter   -c -o compat_strtonum.o compat_strtonum.c
cc -g -W -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter   -c -o main.o main.c
ar rs liblowdown.a autolink.o buffer.o document.o html.o html_escape.o html_smartypants.o library.o log.o nroff.o nroff_escape.o nroff_smartypants.o tree.o xmalloc.o compat_err.o compat_progname.o compat_reallocarray.o compat_strlcat.o compat_strlcpy.o compat_strtonum.o
ar: creating archive liblowdown.a
cc -o lowdown main.o liblowdown.a
Undefined symbols for architecture x86_64:
  "_memrchr", referenced from:
      _rndr in liblowdown.a(nroff.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [lowdown] Error 1

**Comment by kristapsdz** [comment]
Fixed, thanks!
