### ISSUE TITLE
libmd not linked against shared library

### ISSUE THREAD

**Issue by grawlinson** [kristapsdz/lowdown#81]
This particular issue bit me when I packaged lowdown for Arch Linux and proceeded to link against the shared library, ld fails to link due to missing `MD5_` functions.

The following lines from `Makefile` did not include `-lmd` in `LDFLAGS`:
https://github.com/kristapsdz/lowdown/blob/18326467b4d5323245a4aadcc0fe448f8cdaac75/Makefile#L143-L144

I've patched it in [here](https://github.com/archlinux/svntogit-community/blob/790cca27ab85181f40ccb698bda79125b659938c/trunk/shared.patch#L20) downstream, and thought it may be of some use to other consumers of the lowdown library.

**Comment by kristapsdz** [comment]
Thanks, added!  If there are any other differences that would make integration easier, just let me know.
