### ISSUE TITLE
No line should be needed to separate a paragraph from a list

### ISSUE THREAD

**Issue by ericonr** [kristapsdz/lowdown#82]
Hi!

The following markdown:

```
normal paragraph
- list item #1
- list item #2
```

produces a single paragraph in lowdown, but with `cmark` and GitHub's renderer, it creates a paragraph and two list items.

Per https://spec.commonmark.org/0.30/#example-303 , the expected behavior is the 2 list items.

**Comment by kristapsdz** [comment]
Lowdown doesn't implement Commonmark except for one or two features.  If you'd like to submit a patch for this (to be used with `LOWDOWN_COMMONMARK`), then go ahead!
