### ISSUE TITLE
Output non inline images as figures

### ISSUE THREAD

**Issue by The-Night-Watch** [kristapsdz/lowdown#83]
Pandoc comes with an extension enabled by default called [implicit_figures](https://pandoc.org/MANUAL.html#extension-implicit_figures), which is described by the docs as:

> An image with nonempty alt text, occurring by itself in a paragraph, will be rendered as a figure with a caption. The image’s alt text will be used as the caption.

This is a very useful feature in my opinion, especially when using it for static blog generation, as [figures](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure) are a common pattern used in article pages. I love lowdown, but the lack of this feature is making it difficult for me to use it in my current workflow.

I'm willing to work on it myself and submit a PR, but I wanted to check first if that is something the project would be interested in, so I don't work on it for nothing.

**Comment by kristapsdz** [comment]
If you want it, do it.  But please check out whether any other output media supported by lowdown recognise this extension (**-Todt** and **-Tlatex**?).  On a related note, saying "so I don't work on it for nothing" sets a poor tone.  Do it for your own workflow first, or don't.

**Comment by kristapsdz** [comment]
As expected.
