### ISSUE TITLE
broken manpage Name section for commands with subcommands

### ISSUE THREAD

**Issue by thkoch2001** [kristapsdz/lowdown#84]
Given an input file _test.md_ for a command with a subcommand (like e.g. with git):

```
# Name

git log - does something
```

`lowdown -sT man test.md` produces:

```
.\" -*- mode: troff; coding: utf-8 -*-
.TH "Untitled article" "7" ""
.SH Name
git log - does something
```

However in the command name the space should be replaced with an underscore: `git_log`.

Due to this I got a lot of [bad-whatis-entry](https://lintian.debian.org/tags/bad-whatis-entry) warnings from Debian's lintian tool when packaging [nix](https://tracker.debian.org/pkg/nix), which uses lowdown. The lintian explanation says:

> Listed items may not contain any spaces. A manual page for a two-level command such as fs listacl must look like fs_listacl so the list is read correctly.

The [lexgrog manpage](https://manpages.debian.org/bullseye/man-db/lexgrog.1.en.html) confirms:

> Names containing whitespace will be ignored to avoid pathological behaviour on certain ill-formed NAME sections.

**Comment by kristapsdz** [comment]
Do any other markdown formatters do this, that I can reference?

**Comment by kristapsdz** [comment]
I'm closing this out due to lack of further information.  For the record, running `pandoc -tman` on this same input does the same as `lowdown`.
