### ISSUE TITLE
Linker failure on macOS in shared library

### ISSUE THREAD

**Issue by sternenseemann** [kristapsdz/lowdown#87]
Building the lowdown shared object on macOS will currently fail like this:

```
clang -shared -o liblowdown.so.1 autolink.o buffer.o diff.o document.o entity.o gemini.o html.o html_escape.o latex.o library.o libdiff.o nroff.o odt.o smartypants.o term.o tree.o util.o compats.o   -Wl,-soname,liblowdown.so.1
ld: unknown option: -soname
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:168: liblowdown.so] Error 1
```

This is not surprising, as the lack of a `.dylib` target already indicates this is not explicitly supported. The question is, do you want to support it upstream? Would you accept patches?

**Comment by kristapsdz** [comment]
Sure, don't hesitate to patch anything you'd like!

**Comment by kristapsdz** [comment]
This has been fixed in recent commits and will appear in the next version.  Thank you!

**Comment by sternenseemann** [comment]
Can oconfigure determine the file extension for shared objects somehow? A remaining problem on darwin seems to be that it is still installed as `.so` and not `.dylib`. (I also believe the way versioned shared objects are named is different on darwin, but I'd need to look it up.)
