### ISSUE TITLE
Feature request: built-in pikchr support

### ISSUE THREAD

**Issue by data-man** [kristapsdz/lowdown#89]
First of all, thank you for the great tools!

[pikchr](https://pikchr.org) ([GH mirror](https://github.com/drhsqlite/pikchr)) "is a [PIC](https://en.wikipedia.org/wiki/Pic_language)-like markup language for diagrams in technical documentation. Pikchr is designed to be embedded in [fenced code blocks](https://spec.commonmark.org/0.29/#fenced-code-blocks) of Markdown or similar mechanisms of other documentation markup languages."

Just a couple of C-files! :)

So my proposal is this:

````
```pikchr
  some cool Pikchrs
```
````

**Comment by kristapsdz** [comment]
Can't wait!  Please use pull requests for the code or just e-mail me patches, if that's easier for you.

**Comment by data-man** [comment]
> Please use pull requests for the code

Will do. Soon! :tm:

**Comment by sodface** [comment]
See also:
https://github.com/zenomt/pikchr-cmd

**Comment by kristapsdz** [comment]
I'm aware of the implementation---the issue is that it only targets SVG as output.  One of the intents of lowdown is not to make HTML the first-class output citizen.  So pikchr would also need support for terminal outputs, LaTeX, roff (via PIC, probably), etc.  This is the same reason that maths aren't parsed in lowdown.

**Comment by sodface** [comment]
My apologies, the purpose of my comment wasn't to advocate for pikchr support in lowdown. I read your response to the related merge request and understand and respect your position. I thought the linked project might be of interest to people looking for pikchr support in lowdown and finding this issue like I did.

The linked project pre-processes the markdown and replaces the pikchr fenced code with html while passing through the rest of the markdown so it can be further processed by your markdown processor of choice, in my case, lowdown.
