### ISSUE TITLE
Backticks unescaped

### ISSUE THREAD

**Issue by vulcasian** [kristapsdz/lowdown#9]
Backticks are unescaped in MS output.

**Comment by kristapsdz** [comment]
I think you mean *roff* output, yes?  I'm now escaping backticks properly as well as tildes.  (See  [mandoc_char(7) Accents](https://man.openbsd.org/mandoc_char#Accents) for details.  Thanks!

**Comment by vulcasian** [comment]
The "^" also needs to be escaped.

**Comment by kristapsdz** [comment]
Fixed, thanks again!
