### ISSUE TITLE
Documentation for -X and unknown keywords

### ISSUE THREAD

**Issue by sodface** [kristapsdz/lowdown#95]
https://github.com/kristapsdz/lowdown/blob/edca6ce6d5336efb147321a43c47a698de41bb7c/man/lowdown.1#L110

man/lowdown.1 states for `-X` 

> Output the metadata value of keyword or an empty string if not found.

I do not get any empty string, but rather a message that the keyword is unknown.

```
sodco:~$ lowdown -X keywordtest md.test
lowdown: keywordtest: unknown keyword
```
as per:
https://github.com/kristapsdz/lowdown/blob/edca6ce6d5336efb147321a43c47a698de41bb7c/main.c#L571

**Comment by sodface** [comment]
Looking at this again many months later and I think I was confusing stderr output for stdout. Probably could just close this?

**Comment by kristapsdz** [comment]
Yes, the error message is printed to stderr, while an empty string (nothing) is written to the output (standard error or the **-o** file).
