### ISSUE TITLE
Compatibility with YAML metadata blocks

### ISSUE THREAD

**Issue by nsbgn** [kristapsdz/lowdown#97]
Apologies if I am overlooking something!

Markdown syntax is notoriously fragmented. For metadata, lowdown uses [MultiMarkdown](https://fletcherpenney.net/multimarkdown/)-style syntax, but YAML metadata blocks seem to be more standard for that purpose (cf. [pandoc](https://pandoc.org/MANUAL.html#metadata-blocks), [jekyll](https://jekyllrb.com/docs/front-matter/), [nanoc](https://nanoc.app/doc/tutorial/), etcetera).

While some of these tools can be made to accept lowdown's syntax (see pandoc with its `markdown_mmd` or `mmd_title_block` extensions), the reverse is not true. This is problematic to me: I use multiple tools and I would like my documents to be parseable with any one of them. Lowdown has my preference, being the most lightweight, but it is also an outlier in the way it parses metadata.

While full YAML support might be out of scope for lowdown, **I suggest that the parser should accept metadata wrapped in `---\n` to increase compatibility.** Perhaps this functionality should be hidden behind a switch, though I don't immediately see real-world situations where the optional characters would lead to issues.

Note that exactly this approach is also taken in [MultiMarkdown itself](https://fletcher.github.io/MultiMarkdown-6/syntax/metadata.html#metadata).

Thanks and let me know what you think!

**Comment by slakkenhuis** [comment]
Note for anyone else running into this issue: a temporary workaround would be to preprocess the Markdown with a simple `awk`:

    awk 'NR==1 && $0=="---" {x=1} NR>1 {if(x==1 && $0=="---") x=0; else print}'  | lowdown

**Comment by kristapsdz** [comment]
Closed as implemented in #117
